### ISSUE TITLE
Raect Sample issue when using `react-router-dom` built it capabilities

### ISSUE THREAD

**Issue by hammerhg** [yWorks/yfiles-for-html-demos#13]
Using the React sample from [yfiles-for-html-demos/toolkin/react](https://github.com/yWorks/yfiles-for-html-demos/tree/master/demos/toolkit/react) and adding `react-router-dom` built it capabilities to the sample application the Graph is only being rendered for the first time.
The behaviour can be seen here https://github.com/hammerhg/yfiles-react-demo-test.

**To Reproduce**
1. Clone https://github.com/hammerhg/yfiles-react-demo-test
2. Fix the location of the `yfiles-23.0.4-dev.tgz` and `licence.json`
3. `npm install`
4. `npm start`
5.  In the browser window make sure that the graph nodes and edges are visible.
6. Click on the `Other page` link on he top left.
7. Click on the `Graph` link on he top left.
8. Observe that the nodes and edges are not visible.
9. Refresh the page and observes the nodes and edges are visible.

**Expected behavior**
When navigating away and back to the graph page using `react-router-dom` built it capabilities the graph nodes and edges should be rerendered. 

**Screenshots**
Initial state (before browsing to `other-page`)
<img width="2046" alt="Screen Shot 2021-02-07 at 23 49 00" src="https://user-images.githubusercontent.com/2307061/107157723-38e23f00-699f-11eb-91da-09df92c2dbe6.png">

After state (after browsing to back to `graph`)
<img width="2048" alt="Screen Shot 2021-02-07 at 23 49 14" src="https://user-images.githubusercontent.com/2307061/107157728-3c75c600-699f-11eb-8d28-4d45d9705bb2.png">

**Browser (please complete the following information):**
- yFiles HTML version: yfiles 23.0.4
 - Browser [Any]
 - Version [latest]
 - OS: [MacOS, Any]

**Comment by yGuy** [comment]
Thank you for the wonderful report! We are going to look into this ASAP.

**Comment by micschro** [comment]
Thanks to the concise test case, we could easily reproduce the problem. It is caused by the fact that the an internal part of the library sets `position:relative` on the GraphComponent element, which is unnecessary in this case and causes the GraphComponent to have zero height. We will fix this erroneous behavior of the library in a future release. In the meantime, a workaround for this particular sample is to make the `position:absolute` rule in `ReactGraphComponent.css` `!important`: d518d387d 

Thank you again for the detailed report and sorry for the inconvenience.
